import type { Metadata } from 'next'
import { ScientificCalculator } from '@/components/ScientificCalculator'
import { Breadcrumbs } from '@/components/Breadcrumbs'
import { RelatedCalculators } from '@/components/RelatedCalculators'
import { softwareJsonLd, breadcrumbJsonLd } from '@/lib/seo'
import { siteConfig } from '@/lib/site'

export const metadata: Metadata = { title: 'Scientific Calculator Online', description: 'Free scientific calculator with trigonometry, logarithms, exponents, roots, fractions, scientific notation, memory, history, and DEG/RAD/GRAD modes.', alternates: { canonical: '/scientific-calculator' } }
const faqs=[{question:'Can I paste a full expression?',answer:'Yes. Paste or type an expression directly into the expression field, then press Enter or the equals button.'},{question:'Does it support scientific notation?',answer:'Yes. Expressions such as 6.022e23 and 1.380649e-23 are supported.'},{question:'Can I calculate fractions?',answer:'Yes. Enter numeric fractions using slash notation such as 3/8 or (5/6)/(7/9).'}]
export default function Page(){const url=`${siteConfig.url}/scientific-calculator`;return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><Breadcrumbs items={[{name:'Home',href:'/'},{name:'Scientific Calculator'}]}/><header className="max-w-3xl"><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Scientific Calculator Online</h1><p className="mt-4 text-base leading-7 text-zinc-600 dark:text-zinc-400">A browser-based scientific calculator for advanced arithmetic, trigonometry, logarithms, powers, roots, fractions, percentages, scientific notation, and more.</p></header><div className="mt-8"><ScientificCalculator/></div><section className="prose-calculator mt-14 max-w-4xl"><h2 className="text-2xl font-semibold">Scientific calculator functions</h2><p>The calculator supports standard arithmetic plus exponents, square roots, factorials, combinations, permutations, logarithms, trigonometric functions, inverse trigonometric functions, hyperbolic functions, constants, percentages, fractions, and scientific notation.</p><h2 className="mt-10 text-2xl font-semibold">Expression examples</h2><ul><li><code>((3/7) + (5/11)) / ((2/9) - (1/6))</code> for a compound fraction.</li><li><code>sin(37.5) × cos(18.2) + log(125) − ln(3.7)</code> in degree mode.</li><li><code>(6.022e23 × 1.380649e-23 × 298.15) / 101325</code> for a scientific-notation calculation.</li></ul></section><section className="mt-12 max-w-4xl"><h2 className="text-2xl font-semibold">Frequently asked questions</h2><div className="mt-4 divide-y divide-zinc-200 rounded-xl border border-zinc-200 dark:divide-zinc-800 dark:border-zinc-800">{faqs.map(f=><details key={f.question} className="p-4"><summary className="cursor-pointer font-medium">{f.question}</summary><p className="mt-3 text-sm leading-6 text-zinc-500">{f.answer}</p></details>)}</div></section><RelatedCalculators exclude="/scientific-calculator"/>{breadcrumbJsonLd([{name:'Home',url:siteConfig.url},{name:'Scientific Calculator',url}])}{softwareJsonLd('Scientific Calculator Online',metadata.description as string,url)}</div>}
